server:
  port: 8081
  
spring:
  datasource:
    url: jdbc:mysql://mysql_user:3306/UserDB?useSSL=false
    password: pass@word1
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect    show-sql: true 

  application:
    name: USER-SERVICE
    
eureka:  client:    service-url:      defaultZone: http://eureka:8761/eureka
    
  instance:    prefer-ip-address: true