server:
  port: 8081
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/UserDB
    password: pass@word1
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect    show-sql: true 

  application:
    name: USER-SERVICE